export const LANGUAGES = {
  EN: "en",
  RU: "ru",
};

export const lang = {
  [LANGUAGES.EN]: {
    signOut: "Sign out",
    signIn: "Sign in",
    welcome: "Welcome",
    signUp: "Sign up",
    errorMessage: "Error 404. Page not found",
    welcomeMessage: "Welcome to the app",
    graphiQLMessage: "All the most interesting things will be here",
    passwordPlaceholder: "Password",
    anotherPasswordPlacehoder: "Repeat your password.",
    signUpSuccess: "Signup success",
    signInSuccess: "Sign in success",
    logOutSuccess: "Log out success",
    emailIsRequired: "Email is required",
    emailValid: "Email must be a valid email",
    passwordIsRequired: "Password is required",
    passwordLength: "Password length should be at least 8 characters",
    passwordMaxLength: "Password cannot exceed more than 12 characters",
    passwordRequirements:
      "Password must contain at least one number, one uppercase letter, one lowercase letter, and one special character.",
    confirmPasswordIsRequired: "Confirm Password is required",
    confirmPasswordLength: "Password length should be at least 8 characters",
    confirmPasswordMaxLength: "Password cannot exceed more than 12 characters",
    passwordsDoNotMatch: "Passwords do not match",
  },
  [LANGUAGES.RU]: {
    signOut: "Выйти",
    signIn: "Вход",
    welcome: "Стартовая страница",
    signUp: "Регистрация",
    errorMessage: "Ошибка 404. Такая страница не найдена",
    welcomeMessage: "Добро пожаловать в приложение",
    graphiQLMessage: "Все самое интересное будет происходить здесь",
    passwordPlaceholder: "Пароль",
    anotherPasswordPlacehoder: "Повторите ваш пароль.",
    signUpSuccess: "Успешная регистрация",
    signInSuccess: "Успешный вход",
    logOutSuccess: "Выход успешен",
    emailIsRequired: "Email обязателен",
    emailValid: "Email должен быть валидным",
    passwordIsRequired: "Пароль обязателен",
    passwordLength: "Длина пароля должна быть не менее 8 символов",
    passwordMaxLength: "Пароль не может превышать 12 символов",
    passwordRequirements:
      "Пароль должен содержать как минимум одну цифру, одну заглавную букву, одну строчную букву и один специальный символ.",
    passwordsDoNotMatch: "Пароли не совпадают",
  },
};
